### ISSUE TITLE
Catch exception in case finish span fails

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-core#25]
I sometimes see errors when the `FinishRootSpan` event fires here

https://github.com/auxmoney/OpentracingBundle-core/blob/da588caa6f5b76f99d145d1916b2319968fb30f8/EventListener/FinishRootSpanSubscriber.php#L33-L41

Could we wrap the call in try catch ? I would prefer drop the span rather than returning a 500 to the caller.

**Comment by cawolf** [comment]
Hi @eddycharly,

this shouldn't happen at all, at least to the interfaces provided by opentracing. But sure, a tracing error should never ever disturb a user interaction. Since the `FinishCommandSpanSubscriber` would also be affected, I suggest adding the exception handling in `Auxmoney\OpentracingBundle\Internal\PersistenceService`, along with some warning level logging.

Do you want to create a PR for that?

**Comment by eddycharly** [comment]
@cawolf i will open a pr later today. Thanks

**Comment by eddycharly** [comment]
I created the PR.
I think the exception comes from jaeger, when it fails ton send the trace to the agent.
The exception is probably this one : 
https://github.com/jukylin/jaeger-php/blob/b5ed6249512419184e04ce2a91cfb01a3eb310aa/src/Jaeger/UdpClient.php#L63

**Comment by cawolf** [comment]
Fixed with #26
