### ISSUE TITLE
Added a messenger support

### ISSUE THREAD

**Issue by ujwaldhakal** [auxmoney/OpentracingBundle-core#92]
I have added Symfony Messenger support for my use case which was not available by making a separate bundle like this. 

Is it okay to create an addon like this from your OpenTracing bundle core?

Here is the link https://github.com/ujwaldhakal/symfony-opentracing-messenger. Let me know what you think

**Comment by cawolf** [comment]
Hi @ujwaldhakal ,
I like the idea very much. It makes sense to have a separate plugin just for the Symfony Messenger component.

I would like to dig a little deeper in the Symfony Messenger component itself, to be able to give you a high quality feedback on the integration.
However, I already glanced over your repository and saw some improvement opportunities - how should I give you feedback? Issues in your repository? Or just using this issue here in OpentracingBundle-core?

**Comment by ujwaldhakal** [comment]
I think it would be easier to track the issues in my repository.
